### ISSUE TITLE
nodejs cargo test failing under 1.44 nightlies

### ISSUE THREAD

**Issue by shanemadden** [rustyscreeps/screeps-game-api#287] opened 2020-03-26 22:42 UTC
Builds have been failing for several days due to a test failure introduced with the rust 1.44 nightly builds - the `cargo web test --verbose --nodejs` step fails with `thread 'main' panicked at 'internal error: no .js file found', .cargo/registry/src/github.com-1ecc6299db9ec823/cargo-web-0.6.26/src/cmd_test.rs:58:9` - seems like the js files are not being included in the build result artifacts, but I'm unsure if this is an issue in stdweb or rust itself - it doesn't seem likely to be our fault.

I'm planning on putting a PR in to comment out that nodejs test for now, while leaving this issue open to track re-enabling that test when it's not failing in the nightly versions anymore.

**Comment by shanemadden** [comment] 2020-04-15 14:15
Related upstream issue https://github.com/koute/cargo-web/issues/243

**Comment by Azaril** [comment] 2020-04-26 19:30
I root caused this to the .wasm artifact that is generated now gets put under the /target/deps/ folder whereas previously it was just under /target/. This causes it to be explicitly filtered out by cargo-web as they do some modifications to the wasm as a post-process step. I'll report the details on cargo-web and see if I can put together a PR for a fix.

For reference see cargo-web - src\build.rs:

```
fn build_or_check( &self, config: &AggregatedConfig, target: &CargoTarget, should_build: bool ) -> Result< CargoResult, Error > {

...

build_config.build( Some( |artifacts: Vec< PathBuf >| {
                let mut out = Vec::new();
                for path in artifacts {
                    let skip =
                        is_wasm32_unknown_unknown &&
                        path.extension().map( |ext| ext == "wasm" ).unwrap_or( false ) &&
                        path.parent().and_then( |parent| parent.file_name() ).map( |dir| dir == "deps" ).unwrap_or( false );

                    if skip {
                        continue;
                    }

                    if let Some( artifact ) = wasm::process_wasm_file( config.uses_old_stdweb, self.build_args.runtime, &build_config, &prepend_js, target_dir, &path ) {
                        debug!( "Generated artifact: {:?}", artifact );
                        out.push( artifact );
                    }

                    out.push( path );
                }

                out
            }))

```

**Comment by Azaril** [comment] 2020-05-01 03:49
@shanemadden do you want to close this now that @daboross or leave it open for when cargo web fixes the upstream issue?

**Comment by ASalvail** [comment] 2020-05-01 13:26
I prefer the latter, if only to keep a note of the problem.

**Closed** 2023-03-13 19:32 UTC
